#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS final

WORKDIR /app
COPY . .
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Demo1.Api.dll"]