name: ci-demo1
on:
  push:
    branches:
      - main
env:
  REPOSITORY: demo1
  DOCKER_BUILD_FILE_PATH: Dockerfile.build
  DOCKER_FILE_PATH: Dockerfile.publish
  DOCKER_BUILD_CONTEXT: ./publish
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and Test
        run: docker build -f ${{ env.DOCKER_BUILD_FILE_PATH }} -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.REPOSITORY}}:${GITHUB_REF##*/}-${{ github.run_number }} .

      - name: Runs docker
        run: docker run --name demo1 -d ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.REPOSITORY}}:${GITHUB_REF##*/}-${{ github.run_number }}

      - name: copy build files
        run: |
          docker cp demo1:/app/publish/ ./
          docker cp demo1:/testresults/ ./
          docker rm demo1

      - name: publish test results 1
        uses: actions/upload-artifact@v2  # upload test results
        with:
          name: test-results
          path: "**/*.trx"

      - name: Check files
        run: |
          ls -al
          cd testresults
          ls -al
          cd ..

      - name: publish coverage report
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: "coverage.cobertura.xml"

      

      - name: Build and  push image to container registry
        run: |
          docker build -f ${{ env.DOCKER_FILE_PATH }} ${{ env.DOCKER_BUILD_CONTEXT }} -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.REPOSITORY}}:${GITHUB_REF##*/}-${{ github.run_number }}
          # docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.REPOSITORY}}:${GITHUB_REF##*/}-${{ github.run_number }}
